import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-light": "var(--primary-light)",
        secondary: "var(--secondary)",
        accent: "var(--accent)",
        "card-bg": "var(--card-bg)",
        "card-border": "var(--card-border)",
        "card-hover-border": "var(--card-hover-border)",
        success: "var(--success)",
        "success-light": "var(--success-light)",
        error: "var(--error)",
        "error-light": "var(--error-light)",
        warning: "var(--warning)",
        "warning-light": "var(--warning-light)",
        info: "var(--info)",
        "info-light": "var(--info-light)",
        "text-muted": "var(--text-muted)",
        "text-default": "var(--text-default)",
        "text-heading": "var(--text-heading)",
        "table-bg": "var(--table-bg)",
        "table-border": "var(--table-border)",
        "table-text": "var(--table-text)",
      },
      borderColor: {
        DEFAULT: "var(--card-border)",
        "subtle": "var(--border-subtle)",
        "default": "var(--border-default)",
        "emphasis": "var(--border-emphasis)",
      },
      boxShadow: {
        card: "var(--shadow)",
        "card-hover": "var(--shadow-md)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        highlight: "var(--shadow-highlight)",
      },
      animation: {
        "float": "float 8s ease-in-out infinite",
        "float-delay-2": "float 8s ease-in-out infinite 2s",
        "float-delay-4": "float 8s ease-in-out infinite 4s",
        "glow": "glow 4s ease-in-out infinite alternate",
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
      },
      transitionProperty: {
        'height': 'height',
      },
      scale: {
        '102': '1.02',
      },
      transitionDuration: {
        'default': 'var(--animation-default)',
        'fast': 'var(--animation-fast)',
        'slow': 'var(--animation-slow)',
      },
      borderRadius: {
        'sm': 'var(--border-radius-sm)',
        DEFAULT: 'var(--border-radius)',
        'md': 'var(--border-radius-md)',
        'lg': 'var(--border-radius-lg)',
        'xl': 'var(--border-radius-xl)',
        'full': 'var(--border-radius-full)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, var(--button-gradient-from), var(--button-gradient-to))',
        'gradient-primary-hover': 'linear-gradient(135deg, var(--button-hover-from), var(--button-hover-to))',
      },
    },
  },
  plugins: [],
} satisfies Config;
